### ISSUE TITLE
license question

### ISSUE THREAD

**Issue by IzzySoft** [plateaukao/quickrotate#1]
Thanks for making this little tool available! Did you consider adding a license to your project? Without a license it is "all rights reserved", which might keep potential contributors (and users) away.

**Comment by plateaukao** [comment]
Hi, @IzzySoft 

Thanks for your reminding. I added license. :)

**Comment by IzzySoft** [comment]
Great, thanks a lot! That allows me to include your app with my repo – so it will [become available here](https://apt.izzysoft.de/fdroid/index/apk/info.plateaukao.quickrotate) with the next sync tomorrow. Might help to make it better visible – and allows users to easily install and keep it updated using the F-Droid client of their choice. Should you wish to link there, be welcome to [pick a badge for that](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) :smiley:

PS: If you want the description updated or have some screenshots I shall add, just let me know. Would be nice to have an icon, too :wink:
