### ISSUE TITLE
Feature Request: Upside-down button

### ISSUE THREAD

**Issue by noxhirsch** [plateaukao/quickrotate#2]
Hi, 
this is a great little tool - thank you very much!
I often read in bed and turn around a lot. When I use the Reader with the cover, I have to turn the display 180° to be able to hold it with the other hand. It would be cool to have a quick button for toggling between "normal" and "upside-down" :)

**Comment by plateaukao** [comment]
Sure, I will create one for that. :)

**Comment by noxhirsch** [comment]
I love it - thank you very much!

**Comment by plateaukao** [comment]
@noxhirsch  Added in https://github.com/plateaukao/quickrotate/releases/tag/v1.7.0

**Comment by mergen3107** [comment]
Special thanks for headache-less implementation of the rotation! No more stupid extra menus, just rotate to destination and back via single button!! ❤️
