### ISSUE TITLE
wrong APK at tag v1.9.0?

### ISSUE THREAD

**Issue by IzzySoft** [plateaukao/quickrotate#6]
The APK attached to the latest v1.9.0 release identifies as

    package: name='info.plateaukao.quickrotate' versionCode='1080' versionName='1.8'

Is it the wrong APK – or did you just forget to update the version in `build.gradle` before creating it? Could you maybe replace it by the correct one? Thanks in advance!

**Comment by plateaukao** [comment]
it should  be the correct version. Anyways, I rebuilt again and uploaded again. :)

**Comment by IzzySoft** [comment]
Yes, that one looks fine – thanks!

Btw: Your app is [available in my repo](https://apt.izzysoft.de/fdroid/index/apk/info.plateaukao.quickrotate) with updates fetched within 24h of your tagging and attaching an APK (some screenshots and an icon would be appreciated so I'd add them to the listing – you know, first impression, an image speaking louder, and all that). Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme :smiley:

**Comment by plateaukao** [comment]
@IzzySoft 
Thanks for the information. I will update the badge on the README file.

**Comment by IzzySoft** [comment]
Thanks! And should you have some icon/screenshots I should add with the app description, just give me a ping and I'll see to it.
